### ISSUE TITLE
Removing mod and adding back

### ISSUE THREAD

**Issue by hozz1235** [Xpazeman/tld-remove-clutter#3]
Not sure if this is an "issue" or not, but as an experiment, I cleared a room of clutter using the mod, saved game, backed up game, removed mod and loaded game.  As expected, all clutter was back.  I added the mod back, reloaded the backed up save game (with the clutter removed) and the clutter was there again.
I guess this is a pro and a con....a pro in that I can harvest all the clutter again, a con in that I had cleared all maps of all clutter and now I will need to do it again (as I am a completionist).

Anyways, I appreciate all you do and please keep up the awesome work!

**Comment by Xpazeman** [comment]
Yes, the break down data is saved as long as the mod is active. If it is removed and the location is loaded again, vanilla breakdown data will overwrite what was in there. It also can happen when Hinterland does a refresh of locations (with an update or whatever)
