### ISSUE TITLE
Mod not working after 1.93 update

### ISSUE THREAD

**Issue by dommrogers** [Xpazeman/tld-remove-clutter#5]
I can't seem to get the mod to work after the 1.93 update.
*edit: was working on 1.92 fine.

My ongoing save doesn't let me break anything down that isn't already doable ingame.
Tried a new save with only this mod installed, still didn't work.

Was wondering if you were aware and would have any time to look into it ?

Happy to help with any debugging/testing if required.

Thanks,
Dom

**Comment by Hotklou** [comment]
When I first start up a new playthrough, it does indeed not work at first. But I've seen that it starts working again on its own when I've played for a little while. It seems to start working again consistently within the first 48 hours of the playthrough. I've only tested on Survival (Custom), though.

**Comment by Xpazeman** [comment]
That's... really strange, it should work without issues from the start. Will check it out.

**Comment by dommrogers** [comment]
FYI..
I have since started a new Interloper game and it worked right off the bat and still is, very odd.
(same version as previous playthrough where it was broken)

TLD Version : 1.93 71192 S
Modloader output: https://pastebin.com/TC4K275L

Hope this helps, appreciate you replying and looking into it.

**Comment by dommrogers** [comment]
Somewhat redundent :), just cleaning up my GitHub
